# Generated by Django 4.0.4 on 2022-10-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('first_name', models.CharField(max_length=40, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=40, verbose_name='last_name')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('color', models.CharField(max_length=40, verbose_name='color')),
            ],
        ),
    ]
